chapter {* Generated by Lem from error.lem. *}

theory "ErrorAuxiliary" 

imports 
 	 Main "~~/src/HOL/Library/Code_Target_Numeral"
	 "/home/pes20/bitbucket/lem/isabelle-lib/Lem_num" 
	 "/home/pes20/bitbucket/lem/isabelle-lib/Lem_list" 
	 "/home/pes20/bitbucket/lem/isabelle-lib/Lem_basic_classes" 
	 "/home/pes20/bitbucket/lem/isabelle-lib/Lem_maybe" 
	 "/home/pes20/bitbucket/lem/isabelle-lib/Lem_string" 
	 "Show" 
	 "Error" 

begin 


(****************************************************)
(*                                                  *)
(* Termination Proofs                               *)
(*                                                  *)
(****************************************************)

termination repeatM by lexicographic_order

termination repeatM' by lexicographic_order

termination mapM by lexicographic_order

termination foldM by lexicographic_order



end
