(* Claude: the evaluation state at dw_here, as a small text file shared by the linksem
   evaluator and the debugger scripts (which check the live registers against it):

     arch x86_64
     pc dw_here
     cfa 6 16            # CFA = register 6 + 16
     reg 0 dw_mem+0      # DWARF register 0 holds the address dw_mem+0
     reg 1 0x10
     ...

   Memory is not listed: the evaluator reads it from the ELF image, and the program
   does not write memory before dw_here. *)

type t = { arch : string; pc : string; cfa : int * int; regs : (int * Arch.regval) list }

let of_arch (a : Arch.t) = { arch = a.name; pc = "dw_here"; cfa = (a.cfa_reg, a.cfa_off); regs = a.regs }

let string_of_regval = function
  | Arch.Const c -> "0x" ^ Z.format "x" c
  | Arch.Mem off -> Printf.sprintf "dw_mem+%d" off

let regval_of_string s =
  if String.length s > 7 && String.sub s 0 7 = "dw_mem+" then Arch.Mem (int_of_string (String.sub s 7 (String.length s - 7)))
  else Arch.Const (Z.of_string s)

let write path st =
  let oc = open_out path in
  Printf.fprintf oc "# Claude: dwexpr evaluation state, generated by dwexpr_build\narch %s\npc %s\ncfa %d %d\n" st.arch st.pc (fst st.cfa) (snd st.cfa);
  List.iter (fun (r, v) -> Printf.fprintf oc "reg %d %s\n" r (string_of_regval v)) st.regs;
  close_out oc

let read path =
  let ic = open_in path in
  let st = ref { arch = ""; pc = ""; cfa = (0, 0); regs = [] } in
  (try while true do
       let l = String.trim (input_line ic) in
       if l <> "" && l.[0] <> '#' then
         match List.filter (( <> ) "") (String.split_on_char ' ' l) with
         | ["arch"; a] -> st := { !st with arch = a }
         | ["pc"; s] -> st := { !st with pc = s }
         | ["cfa"; r; o] -> st := { !st with cfa = (int_of_string r, int_of_string o) }
         | ["reg"; r; v] -> st := { !st with regs = !st.regs @ [int_of_string r, regval_of_string v] }
         | _ -> failwith ("state file: bad line " ^ l)
     done with End_of_file -> ());
  close_in ic; !st
