(*Generated by Lem from elf_file.lem.*)
open HolKernel Parse boolLib bossLib;
open lem_numTheory lem_listTheory lem_basic_classesTheory lem_boolTheory lem_maybeTheory lem_stringTheory showTheory missing_pervasivesTheory errorTheory byte_sequenceTheory elf_types_native_uintTheory elf_headerTheory string_tableTheory elf_program_header_tableTheory elf_section_header_tableTheory elf_interpreted_sectionTheory elf_interpreted_segmentTheory elf_symbol_tableTheory elf_fileTheory;

val _ = numLib.prefer_num();



open lemLib;
(* val _ = lemLib.run_interactive := true; *)
val _ = new_theory "elf_fileAuxiliary"


(****************************************************)
(*                                                  *)
(* Termination Proofs                               *)
(*                                                  *)
(****************************************************)

(* val gst = Defn.tgoal_no_defn (find_first_not_in_range_def, find_first_not_in_range_ind) *)
val (find_first_not_in_range_rw, find_first_not_in_range_ind_rw) =
  Defn.tprove_no_defn ((find_first_not_in_range_def, find_first_not_in_range_ind),
    cheat (* the termination proof *)
  )
val find_first_not_in_range_rw = save_thm ("find_first_not_in_range_rw", find_first_not_in_range_rw);
val find_first_not_in_range_ind_rw = save_thm ("find_first_not_in_range_ind_rw", find_first_not_in_range_ind_rw);


(* val gst = Defn.tgoal_no_defn (find_first_in_range_def, find_first_in_range_ind) *)
val (find_first_in_range_rw, find_first_in_range_ind_rw) =
  Defn.tprove_no_defn ((find_first_in_range_def, find_first_in_range_ind),
    cheat (* the termination proof *)
  )
val find_first_in_range_rw = save_thm ("find_first_in_range_rw", find_first_in_range_rw);
val find_first_in_range_ind_rw = save_thm ("find_first_in_range_ind_rw", find_first_in_range_ind_rw);


(* val gst = Defn.tgoal_no_defn (compute_differences_def, compute_differences_ind) *)
val (compute_differences_rw, compute_differences_ind_rw) =
  Defn.tprove_no_defn ((compute_differences_def, compute_differences_ind),
    cheat (* the termination proof *)
  )
val compute_differences_rw = save_thm ("compute_differences_rw", compute_differences_rw);
val compute_differences_ind_rw = save_thm ("compute_differences_ind_rw", compute_differences_ind_rw);




val _ = export_theory()

