(*Generated by Lem from memory_image.lem.*)
open HolKernel Parse boolLib bossLib;
open lem_numTheory lem_listTheory lem_setTheory lem_functionTheory lem_basic_classesTheory lem_boolTheory lem_maybeTheory lem_stringTheory lem_assert_extraTheory showTheory lem_sortingTheory lem_set_extraTheory missing_pervasivesTheory byte_sequenceTheory elf_types_native_uintTheory lem_tupleTheory elf_headerTheory lem_mapTheory elf_program_header_tableTheory elf_section_header_tableTheory elf_interpreted_sectionTheory elf_interpreted_segmentTheory elf_symbol_tableTheory elf_fileTheory elf_relocationTheory lem_map_extraTheory multimapTheory;

val _ = numLib.prefer_num();



val _ = new_theory "memory_image"

(*open import Basic_classes*)
(*open import Function*)
(*open import String*)
(*open import Tuple*)
(*open import Bool*)
(*open import List*)
(*open import Sorting*)
(*open import Map*)
(*import Map_extra*)
(*open import Set*)
(*open import Set_extra*)
(*open import Multimap*)
(*open import Num*)
(*open import Maybe*)
(*open import Assert_extra*)
(*open import Show*)

(*open import Byte_sequence*)
(*open import Elf_file*)
(*open import Elf_header*)
(*open import Elf_interpreted_segment*)
(*open import Elf_interpreted_section*)
(*open import Elf_program_header_table*)
(*open import Elf_section_header_table*)
(*open import Elf_symbol_table*)
(*open import Elf_types_native_uint*)
(*open import Elf_relocation*)

(*open import Missing_pervasives*)

(*open import {isabelle} `GCD`*)

(* Now we can define memory images *)

val _ = type_abbrev( "byte_pattern_element" , ``:  word8 option``);
val _ = type_abbrev( "byte_pattern" , ``: byte_pattern_element list``);

(* An element might have an address/offset, and it has some contents. *)
val _ = Hol_datatype `
 element0 = <| startpos :  num option 
                ; length1   :  num option
                ; contents : byte_pattern
                |>`;


(* HMM -- ideally I want to fold these into the memory image notion
 * and the startpos thingy. *)
val _ = type_abbrev( "allocated_symbols_map" , ``: (string, (num # num)) fmap``); (* start, length *)

(* Instead of modelling address calculations (in linker scripts) like so:

type address_expr = natural -> allocated_symbols_map -> natural
                  ( pos     -> environment           -> result address )
                  
   ... we model it as expressions in terms of CursorPosition. HMM.
*) 

val _ = Hol_datatype `
 expr_operand = Var of string
                   | CursorPosition          (* only valid in certain expressions... HMM *)
                   | Constant of num
                   | UnOp of (expr_unary_operation # expr_operand)
                   | BinOp of (expr_binary_operation # expr_operand # expr_operand)
;
expr_unary_operation = Neg of expr_operand
                           | BitwiseInverse of expr_operand
; 
expr_binary_operation = Add of (expr_operand # expr_operand)
                           | Sub of (expr_operand # expr_operand)
                           | BitwiseAnd of (expr_operand # expr_operand)
                           | BitwiseOr of (expr_operand # expr_operand)`;


val _ = Hol_datatype `
 expr_binary_relation = 
    Lt
    | Lte
    | Gt
    | Gte
    | Eq
    | Neq`;


val _ = Hol_datatype `
 expr = 
    False
    | True
    | Not of expr
    | And of (expr # expr)
    | Or of (expr # expr)
    | BinRel of (expr_binary_relation # expr_operand)`;
  (* LH operand is the expr's value *)

(*
val cond_expr : expr -> expr -> expr -> expr
let cond_expr expr1 expr2 expr3 = (Or((And(expr1, expr2)), (And((Not(expr1)), expr3))))
*)

(* Memory image elements all have identities. For convenience
 * we make the identities strings. The string contents are arbitrary,
 * and only their equality is relevant, but choosing friendly names
 * like "ELF header" is good practice.*)
val _ = type_abbrev( "memory_image" , ``: (string, element0) fmap``);

val _ = type_abbrev( "range0" , ``: num # num``); (* start, length *)

val _ = type_abbrev( "element_range" , ``: string # range0``);

(* An "element" of an ELF image, in the linking phase, is either a section,
 * the ELF header, the section header table or the program header table.
 * 
 * PROBLEM: We'd like to use section names as the identifiers
 * for those elements that are sections.
 * but we can't, because they are not guaranteed to be unique. 
 * 
 * SOLUTION: Names that are unique in the file are used as keys. 
 * If not unique, the sections are treated as anonymous and given
 * gensym'd string ids (FIXME: implement this).
 *)

(* Currently, our elements have unique names, which are strings.
 * We *don't* want to encode any meaning onto these strings.
 * All meaning should be encoded into labelled ranges.
 * We want to be able to look up 
 *
 * - elements
 * - ranges within elements
 * 
 * ... by their *labels* -- or sometimes just *part* of their labels.
 *)

(* ELF file features with which we can label ranges of the memory image. *)
val _ = Hol_datatype `
 elf_file_feature = 
    ElfHeader of elf64_header
    | ElfSectionHeaderTable of elf64_section_header_table (* do we want to expand these? *)
    | ElfProgramHeaderTable of elf64_program_header_table
    | ElfSection of (num # elf64_interpreted_section) (* SHT idx *)
    | ElfSegment of (num # elf64_interpreted_segment)`;
 (* PHT idx *)

val _ = Hol_datatype `
 symbol_definition
 = <| def_symname : string
    ; def_syment : elf64_symbol_table_entry (* definition's symtab entry *)
    ; def_sym_scn : num                 (* symtab section index, to disamiguate dynsym *)
    ; def_sym_idx : num                 (* index of symbol into the symtab *)
    ; def_linkable_idx : num            (* used to propagate origin linkable information to linked image *)
    |>`;


val _ = Define `
 (symDefCompare x1 x2=         
(quintupleCompare (\ x y. EQ) elf64_symbol_table_entry_compare (genericCompare (<) (=)) (genericCompare (<) (=)) (genericCompare (<) (=)) (x1.def_symname, x1.def_syment, x1.def_sym_scn, x1.def_sym_idx, x1.def_linkable_idx)
                (x2.def_symname, x2.def_syment, x2.def_sym_scn, x2.def_sym_idx, x2.def_linkable_idx)))`;


val _ = Define `
(instance_Basic_classes_Ord_Memory_image_symbol_definition_dict= (<|

  compare_method := symDefCompare;

  isLess_method := (\ f1 .  (\ f2 .  (symDefCompare f1 f2 = LT)));

  isLessEqual_method := (\ f1 .  (\ f2 .  (IN) (symDefCompare f1 f2) ({LT; EQ})));

  isGreater_method := (\ f1 .  (\ f2 .  (symDefCompare f1 f2 = GT)));

  isGreaterEqual_method := (\ f1 .  (\ f2 .  (IN) (symDefCompare f1 f2) ({GT; EQ})))|>))`;


val _ = Hol_datatype `
 symbol_reference
 = <| ref_symname : string                  (* symbol name *)
    ; ref_syment : elf64_symbol_table_entry (* likely-undefined (referencing) symbol *)
    ; ref_sym_scn : num                 (* symtab section idx *) 
    ; ref_sym_idx : num                 (* index into symbol table *)
    |>`;


val _ = Define `
 (symRefCompare x1 x2=         
(quadrupleCompare (\ x y. EQ) elf64_symbol_table_entry_compare (genericCompare (<) (=)) (genericCompare (<) (=)) (x1.ref_symname, x1.ref_syment, x1.ref_sym_scn, x1.ref_sym_idx)
                (x2.ref_symname, x2.ref_syment, x2.ref_sym_scn, x2.ref_sym_idx)))`;

                
val _ = Define `
(instance_Basic_classes_Ord_Memory_image_symbol_reference_dict= (<|

  compare_method := symRefCompare;

  isLess_method := (\ f1 .  (\ f2 .  (symRefCompare f1 f2 = LT)));

  isLessEqual_method := (\ f1 .  (\ f2 .  (IN) (symRefCompare f1 f2) ({LT; EQ})));

  isGreater_method := (\ f1 .  (\ f2 .  (symRefCompare f1 f2 = GT)));

  isGreaterEqual_method := (\ f1 .  (\ f2 .  (IN) (symRefCompare f1 f2) ({GT; EQ})))|>))`;


val _ = Hol_datatype `
 reloc_site = <|
      ref_relent  : elf64_relocation_a 
    ; ref_rel_scn : num  (* the relocation section idx *)
    ; ref_rel_idx : num  (* the index of the relocation rec *)
    ; ref_src_scn : num  (* the section *from which* the reference logically comes *)
|>`;


val _ = Define `
 (relocSiteCompare x1 x2=         
(quadrupleCompare elf64_relocation_a_compare (genericCompare (<) (=)) (genericCompare (<) (=)) (genericCompare (<) (=)) (x1.ref_relent, x1.ref_rel_scn, x1.ref_rel_idx, x1.ref_src_scn)
                (x2.ref_relent, x2.ref_rel_scn, x2.ref_rel_idx, x2.ref_src_scn)))`;

                
val _ = Define `
(instance_Basic_classes_Ord_Memory_image_reloc_site_dict= (<|

  compare_method := relocSiteCompare;

  isLess_method := (\ f1 .  (\ f2 .  (relocSiteCompare f1 f2 = LT)));

  isLessEqual_method := (\ f1 .  (\ f2 .  (IN) (relocSiteCompare f1 f2) ({LT; EQ})));

  isGreater_method := (\ f1 .  (\ f2 .  (relocSiteCompare f1 f2 = GT)));

  isGreaterEqual_method := (\ f1 .  (\ f2 .  (IN) (relocSiteCompare f1 f2) ({GT; EQ})))|>))`;

    
val _ = Hol_datatype `
 reloc_decision = LeaveReloc
                    | ApplyReloc
                    | ChangeRelocTo of (num # symbol_reference # reloc_site)`;

                    (* | MakePIC    -- is now a kind of ChangeRelocTo *)

val _ = Define `
 (relocDecisionCompare x1 x2=  
 ((case (x1, x2) of
      (LeaveReloc, LeaveReloc) => EQ
    | (LeaveReloc, _)          => LT
    | (ApplyReloc, ApplyReloc) => EQ
    | (ApplyReloc, ChangeRelocTo _) => LT
    | (ApplyReloc, LeaveReloc)      => GT
    | (ChangeRelocTo t1, ChangeRelocTo t2) => (tripleCompare (genericCompare (<) (=)) symRefCompare relocSiteCompare t1 t2)
    | (ChangeRelocTo _, _) => GT
  )))`;


val _ = Define `
(instance_Basic_classes_Ord_Memory_image_reloc_decision_dict= (<|

  compare_method := relocDecisionCompare;

  isLess_method := (\ f1 .  (\ f2 .  (relocDecisionCompare f1 f2 = LT)));

  isLessEqual_method := (\ f1 .  (\ f2 .  (IN) (relocDecisionCompare f1 f2) ({LT; EQ})));

  isGreater_method := (\ f1 .  (\ f2 .  (relocDecisionCompare f1 f2 = GT)));

  isGreaterEqual_method := (\ f1 .  (\ f2 .  (IN) (relocDecisionCompare f1 f2) ({GT; EQ})))|>))`;


val _ = Hol_datatype `
 symbol_reference_and_reloc_site = <|
      ref         : symbol_reference
    ; maybe_reloc :  reloc_site option
    ; maybe_def_bound_to :  (reloc_decision #  symbol_definition option)option
    |>`;


val _ = Define `
 (symRefAndRelocSiteCompare x1 x2=         
(tripleCompare symRefCompare (maybeCompare relocSiteCompare) (maybeCompare (pairCompare relocDecisionCompare (maybeCompare symDefCompare))) (x1.ref, x1.maybe_reloc, x1.maybe_def_bound_to)
                (x2.ref, x2.maybe_reloc, x2.maybe_def_bound_to)))`;


val _ = Define `
(instance_Basic_classes_Ord_Memory_image_symbol_reference_and_reloc_site_dict= (<|

  compare_method := symRefAndRelocSiteCompare;

  isLess_method := (\ f1 .  (\ f2 .  (symRefAndRelocSiteCompare f1 f2 = LT)));

  isLessEqual_method := (\ f1 .  (\ f2 .  (IN) (symRefAndRelocSiteCompare f1 f2) ({LT; EQ})));

  isGreater_method := (\ f1 .  (\ f2 .  (symRefAndRelocSiteCompare f1 f2 = GT)));

  isGreaterEqual_method := (\ f1 .  (\ f2 .  (IN) (symRefAndRelocSiteCompare f1 f2) ({GT; EQ})))|>))`;


(* We can also annotate arbitrary ranges of bytes within an element
 * with arbitrary metadata. 
 * 
 * Ideally we want to data-abstract this a bit. But it's hard to do
 * so without baking in ELF-specific and/or (moreover) per-ABI concepts, 
 * like PLTs and GOTs. Ideally we would use something like polymorphic
 * variants here. For now, this has to be the union of all the concepts
 * that we find in the various ABIs we care about. To avoid ELFy things
 * creeping in, we parameterise by 'a, and instantiate the 'a with the
 * relevant ELFy thing when we use it. OH, but then 'a is different for
 * every distinct ELF thing, which is no good. Can we define a mapping
 * from an umbrella "ELF" type to the relevant types in each case? *)
val _ = Hol_datatype `
 range_tag = (*  forall 'abifeature . *)
                 ImageBase
               | EntryPoint
               | SymbolDef of symbol_definition
               | SymbolRef of symbol_reference_and_reloc_site
               | FileFeature of elf_file_feature (* file feature other than symdef and reloc *)
               | AbiFeature of 'abifeature`;


val _ = Hol_datatype `
(*  'abifeature *) annotated_memory_image = <|
      elements         : memory_image 
    ; by_range         : (( element_range option) # ( 'abifeature range_tag)) set
    ; by_tag           : (( 'abifeature range_tag), ( element_range option)) multimap
|>`;


(*val get_empty_memory_image : forall 'abifeature. unit -> annotated_memory_image 'abifeature*)
val _ = Define `
 (get_empty_memory_image= 
  (\u .  (case (u ) of
             ( _ ) => <| elements := FEMPTY ; by_range := EMPTY
                        ; by_tag := EMPTY|>
         )))`;


(* Basic ELFy and ABI-y things. *)
(* "Special" sections are those that necessarily require special treatment by the 
 * linker. Examples include symbol tables and relocation tables. There are some
 * grey areas, such as .eh_frame, debug info, and string tables. For us, the rule
 * is that if we have special code to create them, i.e. that we don't rely on
 * ordinary section concatenation during the linker script interpretation, they
 * should be special -- it means strip_metadata_sections will remove them from
 * the image, they won't be seen by the linker script, and that it's *our* job
 * to reinstate them afterwards (as we do with symtab and strtab, for example). *)
(* FIXME: this shouldn't really be here, but needs to be in some low-lying module;
 * keeping it out of elf_* for now to avoid duplication into elf64_, elf32_. *)
val _ = Define `
 (elf_section_is_special s f=  (~ (s.elf64_section_type = sht_progbits)
                     /\ ~ (s.elf64_section_type = sht_nobits)
                     /\ ~ (s.elf64_section_type = sht_fini_array)
                     /\ ~ (s.elf64_section_type = sht_init_array)))`;


(* This record collects things that ABIs may or must define. 
 * 
 * Since we want to put all ABIs in a list and select one at run time, 
 * we can't maintain a type-level distinction between ABIs; we have to
 * use elf_memory_image any_abi_feature. To avoid a reference cycle,
 * stay polymorphic in the ABI feature type until we define specific ABIs.
 * In practice we'll use only any_abi_feature, because we need to pull
 * the ABI out of a list at run time.
 *)
val _ = type_abbrev( "null_abi_feature" , ``: unit``);

(* The reloc calculation is complicated, so we split up the big function
 * type into smaller ones. *)

(* Q. Do we want "existing", or is it a kind of addend? 
 * A. We do want it -- modelling both separately is necessary, 
 * because we model relocations bytewise, but some arches
 * do bitfield relocations (think ARM). *)
val _ = type_abbrev( "reloc_calculate_fn"    , ``: num -> int -> num -> num``); (* symaddr -> addend -> existing -> relocated *)

val _ = type_abbrev((*  'abifeature *) "reloc_apply_fn" , ``: 'abifeature 
                                (* elf memory image: the context in which the relocation is being applied *)
                                annotated_memory_image ->
                               (* the site address *)
                                num ->
                                (* Typically there are two symbol table entries involved in a relocation.
                                 * One is the reference, and is usually undefined.
                                 * The other is the definition, and is defined (else absent, when we use 0).
                                 * However, sometimes the reference is itself a defined symbol.
                                 * Almost always, if so, *that* symbol *is* "the definition".
                                 * However, copy relocs are an exception.
                                 * 
                                 * In the case of copy relocations being fixed up by the dynamic
                                 * linker, the dynamic linker must figure out which definition to
                                 * copy from. This can't be as simple as "the first definition in
                                 * link order", because *our* copy of that symbol is a definition
                                 * (typically in bss). It could be as simple as "the first *after us*
                                 * in link order". FIXME: find the glibc code that does this.
                                 * 
                                 * Can we dig this stuff out of the memory image? If we pass the address
                                 * being relocated, we can find the tags. But I don't want to pass
                                 * the symbol address until the very end. It seems better to pass the symbol
                                 * name, since that's the key that the dynamic linker uses to look for
                                 * other definitions.
                                 * 
                                 * Do we want to pass a whole symbol_reference? This has not only the
                                 * symbol name but also syment, scn and idx. The syment is usually UND, 
                                 * but *could* be defined (and is for copy relocs). The scn and idx are
                                 * not relevant, but it seems cleaner to pass the whole thing anyway.
                                 *)
                                symbol_reference_and_reloc_site -> 
                                (* Should we pass a symbol_definition too? Implicitly, we pass part of it
                                 * by passing the symaddr argument (below). I'd prefer not to depend on
                                 * others -- relocation calculations should look like "mostly address 
                                 * arithmetic", i.e. only the weird ones do something else. *)
                                 (* How wide, in bytes, is the relocated field? this may depend on img 
                                 * and on the wider image (copy relocs), so it's returned *by* the reloc function. *)
                                (num (* width *) # reloc_calculate_fn)``);

(* Some kinds of relocation necessarily give us back a R_*_RELATIVE reloc.
 * We don't record this explicitly. Instead, the "bool" is a flag recording whether
 * the field represents an absolute address.
 * Similarly, some relocations can "fail" according to their ABI manuals.
 * This just means that the result can't be represented in the field width.
 * We detect this when actually applying the reloc in the memory image content
 * (done elsewhere). *)
val _ = type_abbrev((*  'abifeature *) "reloc_fn" , ``: num -> (bool # 'abifeature reloc_apply_fn)``);

(*val noop_reloc_calculate : natural -> integer -> natural -> natural*)
val _ = Define `
 (noop_reloc_calculate symaddr addend existing=  existing)`;


(*val noop_reloc_apply : forall 'abifeature. reloc_apply_fn 'abifeature*)
val _ = Define `
 (noop_reloc_apply img site_addr ref=  (( 0:num), noop_reloc_calculate))`;


(*val noop_reloc : forall 'abifeature. natural -> (bool (* result is absolute addr *) * reloc_apply_fn 'abifeature)*)
val _ = Define `
 (noop_reloc k=  (F, noop_reloc_apply))`;


val _ = Hol_datatype `
(*  'abifeature *) abi = (* forall 'abifeature. *)
   <| is_valid_elf_header : elf64_header -> bool (* doesn't this generalise outrageously? is_valid_elf_file? *)
    ; make_elf_header    : num -> num -> num -> num -> num -> num -> num -> elf64_header
                           (* t entry shoff phoff phnum shnum shstrndx *)
    ; reloc              : 'abifeature reloc_fn
    ; section_is_special : elf64_interpreted_section -> 'abifeature annotated_memory_image -> bool
    ; section_is_large   : elf64_interpreted_section -> 'abifeature annotated_memory_image -> bool
    ; maxpagesize        : num
    ; minpagesize        : num
    ; commonpagesize     : num
    ; symbol_is_generated_by_linker : string -> bool
    (*; link_inputs_tap    : 
    ; link_output_sections_tap   : 
    ; link_output_image_tap      : *)
    ; make_phdrs         : num -> num -> num (* file type *) -> 'abifeature annotated_memory_image -> elf64_interpreted_section list -> elf64_program_header_table_entry list
    ; max_phnum          : num
    ; guess_entry_point  : 'abifeature annotated_memory_image ->  num option
    ; pad_data           : num -> word8 list
    ; pad_code           : num -> word8 list
    ; generate_support   : (string # 'abifeature annotated_memory_image) (* list (list reloc_site_resolution) ->  *)list -> 'abifeature annotated_memory_image
    ; concretise_support : 'abifeature annotated_memory_image -> 'abifeature annotated_memory_image
    ; get_reloc_symaddr  : symbol_definition -> 'abifeature annotated_memory_image ->  reloc_site option -> num
    |>`;


(*val align_up_to : natural -> natural -> natural*)
val _ = Define `
 (align_up_to align addr=    
  (let quot1 = (addr DIV align)
    in
    if (quot1 * align) = addr then addr else (quot1 +( 1:num)) * align))`;


(*val round_down_to : natural -> natural -> natural*)
val _ = Define `
 (round_down_to align addr=    
  (let quot1 = (addr DIV align)
    in
    quot1 * align))`;


(*val uint32_max : natural*)
val _ = Define `
 (uint32_max=  ((( 2:num) **( 32 : num)) -( 1:num)))`;


(*val uint64_max : natural*)
val _ = Define `
 (uint64_max=    
 (((
    (* HACK around Lem's inability to parse 18446744073709551615: 
     * the square of uint32_max is 
     *       (2**32 - 1) (2**32 - 1)
     * i.e.   2**64 - 2**32 - 2**32 + 1
     * So
     * 2**64 - 1 =  uint32_max * uint32_max  + 2**32 + 2**32 - 2
     *)uint32_max * uint32_max) -( 2:num)) + (( 2:num)**( 33 : num))))`;

    (* 18446744073709551615 *) (* i.e. 0x ffff ffff ffff ffff *)
    (* HMM. This still overflows int64 *)

(* The 2's complement of a value, at 64-bit width *)
(*val compl64 : natural -> natural*)
val _ = Define `
 (compl64 v= (( 1:num) + (natural_lxor v uint64_max)))`;


(*val gcd : natural -> natural -> natural*)
 val gcd_defn = Hol_defn "gcd" `
 (gcd a b=    
  (if b =( 0:num) then a else gcd b (a MOD b)))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn gcd_defn;

(*val lcm : natural -> natural -> natural*)
val _ = Define `
 (lcm a b=    
(  
    (* let _ = errln ("lcm of " ^ (show a) ^ " and " ^ (show b) ^ "?")
    in *)(a * b) DIV (gcd a b)))`;


(*val address_of_range : forall 'abifeature. element_range -> annotated_memory_image 'abifeature -> natural*)
val _ = Define `
 (address_of_range el_range img=    
  (let (el_name, (start, len)) = el_range
    in
    (case FLOOKUP img.elements el_name of
        SOME el =>
            (case el.startpos of
                SOME addr => addr + start
                | NONE => failwith "address_of_range called for element with no address"
            )
        | NONE => failwith "address_of_range called on nonexistent element"
    )))`;


(*val range_contains : (natural * natural) -> (natural * natural) -> bool*)
val _ = Define `
 (range_contains (r1begin, r1len) (r2begin, r2len)=
     (( 
    (* r1 is at least as big as r2 *)r2begin >= r1begin) /\ ((r2begin + r2len) <= (r1begin + r1len))))`;


(*val range_overlaps : (natural * natural) -> (natural * natural) -> bool*)
val _ = Define `
 (range_overlaps (r1begin, r1len) (r2begin, r2len)=    
 (((r1begin < (r2begin + r2len)) /\ ((r1begin + r1len) > r2begin))
     \/ ((r2begin < (r1begin + r1len)) /\ ((r2begin + r2len) > r1begin))))`;

    
(*val is_partition : list (natural * natural) -> list (natural * natural) -> bool*)
val _ = Define `
 (is_partition rs ranges=    
(  
    (* 1. each element of the first list falls entirely within some element
     * from the second list. *)let r_is_contained_by_some_range
     = (\ r .  FOLDL (\/) F (MAP (\ range1 .  range_contains range1 r) ranges))
    in
    EVERY (\ r .  r_is_contained_by_some_range r) rs
    /\
    (* 2. elements of the first list do not overlap *)
    EVERY (\ r .  EVERY (\ r2 .  (r = (* should be "=="? *) r2) \/ (~ (range_overlaps r r2))) rs) rs))`;


(*val     nat_range : natural -> natural -> list natural*)
 val nat_range_defn = Hol_defn "nat_range" `
 (nat_range base len=    
 ((case len of 
        0 => []
    |   _ => base :: (nat_range (base +( 1:num)) (len -( 1:num)))
    )))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn nat_range_defn;

(* Expand a sorted list of ranges into a list of bool, where the list contains
 * true if its index is included in one or more ranges, else false. *)
(*val expand_sorted_ranges : list (natural * natural) -> natural -> list bool -> list bool*)
 val expand_sorted_ranges_defn = Hol_defn "expand_sorted_ranges" `
 (expand_sorted_ranges sorted_ranges min_length accum=    
 ((case sorted_ranges of
        [] => accum ++ (
            let pad_length = (MAX(( 0:num)) (min_length - (missing_pervasives$length accum)))
            in
            (* let _ = Missing_pervasives.errln (
                "padding ranges cares list with " ^ (show pad_length) ^ 
                " cares (accumulated " ^ (show (Missing_pervasives.length accum)) ^ 
                ", min length " ^ (show min_length) ^ ")")
            in *)
            missing_pervasives$replicate pad_length T)
     |  (base, len) :: more => 
            (* pad the accum so that it reaches up to base *)
            let up_to_base = (missing_pervasives$replicate (base - (missing_pervasives$length accum)) T)
            in
            let up_to_end_of_range = (up_to_base ++ (missing_pervasives$replicate len F))
            in
            expand_sorted_ranges more min_length (accum ++ up_to_end_of_range)
    )))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn expand_sorted_ranges_defn;

(*val expand_unsorted_ranges : list (natural * natural) -> natural -> list bool -> list bool*)
 val _ = Define `
 (expand_unsorted_ranges unsorted_ranges min_length accum=    
 (expand_sorted_ranges (QSORT (\ (base1, len1) .  (\ (base2, len2) .  base1 < base2)) unsorted_ranges) min_length accum))`;


(*val make_byte_pattern_revacc : list (maybe byte) -> list byte -> list bool -> list (maybe byte)*)
 val make_byte_pattern_revacc_defn = Hol_defn "make_byte_pattern_revacc" `
 (make_byte_pattern_revacc revacc bytes cares=    
  ((case bytes of
          [] => REVERSE revacc
        | b :: bs => (case cares of 
                care :: more => make_byte_pattern_revacc ((if ~ care then NONE else SOME b) :: revacc) bs more
              | _ => failwith "make_byte_pattern: unequal length"
              )
    )))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn make_byte_pattern_revacc_defn;

(*val make_byte_pattern : list byte -> list bool -> list (maybe byte)*)
 val _ = Define `
 (make_byte_pattern bytes cares=    
  (make_byte_pattern_revacc [] bytes cares))`;


(*val relax_byte_pattern_revacc : list (maybe byte) -> list (maybe byte) -> list bool -> list (maybe byte)*)
 val relax_byte_pattern_revacc_defn = Hol_defn "relax_byte_pattern_revacc" `
 (relax_byte_pattern_revacc revacc bytes cares=    
  ((case bytes of
          [] => REVERSE revacc
        | b :: bs => (case cares of 
                care :: more => relax_byte_pattern_revacc ((if ~ care then NONE else b) :: revacc) bs more
              | _ => failwith ("relax_byte_pattern: unequal length")
              )
    )))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn relax_byte_pattern_revacc_defn;
    
(*val relax_byte_pattern : list (maybe byte) -> list bool -> list (maybe byte)*)
 val _ = Define `
 (relax_byte_pattern bytes cares=    
  (relax_byte_pattern_revacc [] bytes cares))`;


val _ = type_abbrev( "pad_fn" , ``: num -> word8 list``);

(*val concretise_byte_pattern : list byte -> natural -> list (maybe byte) -> pad_fn -> list byte*)
 val concretise_byte_pattern_defn = Hol_defn "concretise_byte_pattern" `
 (concretise_byte_pattern rev_acc acc_pad bs pad=    
  ((case bs of
        [] => 
            let padding_bytes = (if acc_pad >( 0:num) then pad acc_pad else [])
            in REVERSE ((REVERSE padding_bytes) ++ rev_acc)
        | SOME(b) :: more => 
            (* flush accumulated padding *)
            let padding_bytes = (if acc_pad >( 0:num) then pad acc_pad else [])
            in
            concretise_byte_pattern (b :: ((REVERSE padding_bytes) ++ rev_acc))(( 0:num)) more pad
        | NONE :: more => 
            concretise_byte_pattern rev_acc (acc_pad+( 1:num)) more pad
    )))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn concretise_byte_pattern_defn;

(*val byte_option_matches_byte : maybe byte -> byte -> bool*)
val _ = Define `
 (byte_option_matches_byte optb b=    
 ((case optb of 
            NONE => T 
        |   SOME some1 => some1 = b 
    )))`;


(*val byte_list_matches_pattern : list (maybe byte) -> list byte -> bool*)
 val byte_list_matches_pattern_defn = Hol_defn "byte_list_matches_pattern" `
 (byte_list_matches_pattern pattern bytes=    
  ((case pattern of 
        [] => T
        | optbyte :: more => (case bytes of 
                [] => F
                | abyte :: morebytes => 
                    byte_option_matches_byte optbyte abyte 
                 /\ byte_list_matches_pattern more morebytes
            )
    )))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn byte_list_matches_pattern_defn;

(*val append_to_byte_pattern_at_offset : natural -> list (maybe byte) -> list (maybe byte) -> list (maybe byte)*)
val _ = Define `
 (append_to_byte_pattern_at_offset offset pat1 pat2=    
 (let pad_length = (offset - missing_pervasives$length pat1)
    in
    if pad_length <( 0:num) then failwith "can't append at offset already used"
    else (pat1 ++ (REPLICATE ( pad_length) NONE)) ++ pat2))`;


(*val accum_pattern_possible_starts_in_one_byte_sequence : list (maybe byte) -> nat -> list byte -> nat -> natural -> list natural -> list natural*)
 val accum_pattern_possible_starts_in_one_byte_sequence_defn = Hol_defn "accum_pattern_possible_starts_in_one_byte_sequence" `
 (accum_pattern_possible_starts_in_one_byte_sequence pattern pattern_len seq seq_len offset accum=    
( 
    (* let _ = Missing_pervasives.errs ("At offset " ^ (show offset) ^ "... ")
    in *)(case pattern of
        [] => (* let _ = Missing_pervasives.errs ("terminating with hit (empty pattern)\n") in *)
            offset :: accum
        | bpe :: more_bpes => (* nonempty, so check for nonempty seq *)
            (case seq of 
                [] => (*let _ = Missing_pervasives.errs ("terminating with miss (empty pattern)\n") 
                    in *) accum (* ran out of bytes in the sequence, so no match *)
                | byte :: more_bytes => let matched_this_byte =                            
 (byte_option_matches_byte bpe byte)
                       in
                       (* let _ = Missing_pervasives.errs ("Byte " ^ (show byte) ^ " matched " ^ (show byte_pattern) ^ "? " ^ (show matched_this_byte) ^ "; ") 
                       in *)
                       let sequence_long_enough = (seq_len >= pattern_len) 
                       in
                       (* let _ = Missing_pervasives.errs ("enough bytes remaining (" ^ (show seq_len) ^ ") to match rest of pattern (" ^ (show pattern_len) ^ ")? " ^ (show sequence_long_enough) ^ "; ") 
                       in *)
                       let matched_here = (matched_this_byte /\ sequence_long_enough /\
                        byte_list_matches_pattern more_bpes more_bytes)
                       in
                       (* let _ = Missing_pervasives.errs ("matched pattern anchored here? " ^ (show matched_this_byte) ^ "\n") 
                       in *)
                       accum_pattern_possible_starts_in_one_byte_sequence 
                           pattern pattern_len 
                           more_bytes (seq_len -( 1 : num)) 
                           (offset +( 1:num)) 
                           (if matched_here then offset :: accum else accum)
            )
    )))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn accum_pattern_possible_starts_in_one_byte_sequence_defn;

val _ = Define `
 (swap_pairs s= 
  ({ (v, k) | k, v | ((k, v) IN s) /\ T }))`;


val _ = Define `
 (by_range_from_by_tag=  swap_pairs)`;


val _ = Define `
 (by_tag_from_by_range=  swap_pairs)`;


(*val filter_elements : forall 'abifeature. ((string * element) -> bool) -> 
    annotated_memory_image 'abifeature -> annotated_memory_image 'abifeature*)
val _ = Define `
 (filter_elements pred img=    
  (let new_elements = (FUPDATE_LIST FEMPTY (let x2 = 
  ([]) in  FOLDR
   (\(n, r) x2 . 
    if
    let result = (pred (n, r)) in
    if ~ result then
      (*let _ = Missing_pervasives.outln ("Discarding element named " ^ n) in*) result
    else result then (n, r) :: x2 else x2) x2
   (SET_TO_LIST (FMAP_TO_SET img.elements))))
    in
    let new_by_range =  (SET_FILTER (\ (maybe_range, tag) .  (case maybe_range of
            NONE => T
            | SOME (el_name, el_range) => el_name IN FDOM new_elements
        )) img.by_range)
    in
    let new_by_tag = ({ (v, k) | k, v | ((k, v) IN new_by_range) /\ T })
    in
    <| elements := new_elements
     ; by_range := new_by_range
     ; by_tag   := new_by_tag
     |>))`;


(*val tag_image : forall 'abifeature. range_tag 'abifeature -> string -> natural -> natural -> annotated_memory_image 'abifeature
    ->  annotated_memory_image 'abifeature*)
val _ = Define `
 (tag_image t el_name el_offset tag_len img=    
  (let (k, v) = (SOME (el_name, (el_offset, tag_len)), t)
    in
    let new_by_range = ((k, v) INSERT img.by_range)
    in
    let new_by_tag = ((v, k) INSERT img.by_tag)
    in
    <| elements := (img.elements)
     ; by_range := new_by_range
     ; by_tag   := new_by_tag
     |>))`;


(*val address_to_element_and_offset : forall 'abifeature. natural -> annotated_memory_image 'abifeature -> maybe (string * natural)*)
val _ = Define `
 (address_to_element_and_offset query_addr img=    
(  
    (* Find the element with the highest address <= addr.
     * What about zero-length elements?
     * Break ties on the bigger size. *)let (maybe_highest_le :  (num # string # element0)option)
     = (FOLDL (\ maybe_current_max_le .  (\ (el_name, el_rec) . 
        (*let _ = errln ("Saw element named `" ^ el_name ^ " with startpos " ^ (
            (match el_rec.startpos with Just addr -> ("0x" ^ (hex_string_of_natural addr)) | Nothing -> "(none)" end)
            ^ " and length " ^
            (match el_rec.length with Just len -> ("0x" ^ (hex_string_of_natural len)) | Nothing -> "(none)" end)
            ))
        in*)
        (case (maybe_current_max_le, el_rec.startpos) of
              (NONE,                                    NONE) => NONE
            | (NONE,                                    SOME this_element_pos) => if this_element_pos <= query_addr 
                                                                                     then SOME (this_element_pos, el_name, el_rec) 
                                                                                     else NONE
            | (SOME (cur_max_le, cur_el_name, cur_el_rec), NONE) =>               maybe_current_max_le
            | (SOME (cur_max_le, cur_el_name, cur_el_rec), SOME this_element_pos) => if (this_element_pos <= query_addr) 
                                                                                        /\ ((this_element_pos > cur_max_le) 
                                                                                         \/ ((this_element_pos = cur_max_le)
                                                                                             /\ (cur_el_rec.length1 = SOME(( 0:num)))))
                                                                                        then SOME (this_element_pos, el_name, el_rec) 
                                                                                        else maybe_current_max_le
        )
    )) NONE (MAP_TO_LIST img.elements))
    in
    (case maybe_highest_le of
        SOME (el_def_startpos, el_name, el_rec) =>
            (* final sanity check: is the length definite, and if so, does the
             * element span far enough? *)
            (case el_rec.length1 of
                SOME l => if (el_def_startpos + l) >= query_addr 
                    then SOME (el_name, (query_addr - el_def_startpos)) 
                    else 
                        (*let _ = errln ("Discounting " ^ el_name ^ " because length is too short") in*) NONE
                | NONE => (*let _ = errln ("Gave up because element has unknown length") in*) NONE
            )
        | NONE => 
            (* no elements with a low enough assigned address, so nothing *)
            (*let _ = errln ("Found no elements with low enough address") in*) NONE
    )))`;

    
(*val element_and_offset_to_address : forall 'abifeature. (string * natural) -> annotated_memory_image 'abifeature -> maybe natural*)
val _ = Define `
 (element_and_offset_to_address (el_name, el_off) img=    
  ((case FLOOKUP img.elements el_name of
        SOME el => (case el.startpos of
                        SOME addr => SOME (addr + el_off)
                        | NONE => NONE
                   )
        | NONE => failwith ( STRCAT"error: nonexistent element: " el_name)
    )))`;


val _ = Define `
 (null_symbol_reference=  (<|
    ref_symname := ""
    ; ref_syment := elf64_null_symbol_table_entry
    ; ref_sym_scn :=(( 0:num))
    ; ref_sym_idx :=(( 0:num))
|>))`;


val _ = Define `
 (null_elf_relocation_a=  
 (<| elf64_ra_offset := ((n2w : num -> uint64) (( 0:num)))  
   ; elf64_ra_info   := ((n2w : num -> uint64) (( 0:num))) 
   ; elf64_ra_addend := ((i2w (( 0 : int))))
   |>))`;



val _ = Define `
 (null_symbol_reference_and_reloc_site=  (<|
      ref := null_symbol_reference
    ; maybe_reloc :=        
 (SOME   <| ref_relent := null_elf_relocation_a
                ; ref_rel_scn :=(( 0:num))
                ; ref_rel_idx :=(( 0:num))
                ; ref_src_scn :=(( 0:num))
                |>)
    ; maybe_def_bound_to := NONE
    |>))`;


val _ = Define `
 (null_symbol_definition=  (<|
    def_symname := ""
    ; def_syment := elf64_null_symbol_table_entry
    ; def_sym_scn :=(( 0:num))
    ; def_sym_idx :=(( 0:num))
    ; def_linkable_idx :=(( 0:num))
|>))`;

    
(*val pattern_possible_starts_in_one_byte_sequence : list (maybe byte) -> list byte -> natural -> list natural*)
val _ = Define `
 (pattern_possible_starts_in_one_byte_sequence pattern seq offset=    
( 
    (* let _ = Missing_pervasives.errs ("Looking for matches of " ^
        (show (List.length pattern)) ^ "-byte pattern in " ^ (show (List.length seq)) ^ "-byte region\n")
    in *)accum_pattern_possible_starts_in_one_byte_sequence pattern (LENGTH pattern) seq (LENGTH seq) offset []))`;


(*val byte_pattern_of_byte_sequence : byte_sequence -> list (maybe byte)*)
val _ = Define `
 (byte_pattern_of_byte_sequence seq=  ((case seq of
    Sequence(bs) => MAP (\ b .  SOME b) bs
)))`;


(*val compute_virtual_address_adjustment : natural -> natural -> natural -> natural*)
val _ = Define `
 (compute_virtual_address_adjustment max_page_size offset vaddr=  
 ((vaddr - offset) MOD max_page_size))`;


(*val extract_natural_field : natural -> element -> natural -> natural*)
val _ = Define `
 (extract_natural_field width element1 offset=    
(  
    (* Read n bytes from the contents *)let maybe_bytes = (take width (drop offset element1.contents))
    in
    let bytes = (MAP (\ mb .  (case mb of NONE => (n2w : num -> 8 word(( 0:num))) | SOME mb => mb )) maybe_bytes)
    in
    (* FIXME: do we want little- or big-endian? *)
    FOLDL (\ acc .  \ next_byte .         
(acc *( 256:num)) + (w2n next_byte)
    ) (( 0:num) : num) bytes))`;


(*val natural_to_le_byte_list : natural -> list byte*)
 val natural_to_le_byte_list_defn = Hol_defn "natural_to_le_byte_list" `
 (natural_to_le_byte_list n=    
  (((n2w : num -> 8 word (n MOD( 256:num)))) :: (let d = (n DIV( 256:num)) in if d =( 0:num) then [] else natural_to_le_byte_list (n DIV( 256:num)))))`;

val _ = Lib.with_flag (computeLib.auto_import_definitions, false) Defn.save_defn natural_to_le_byte_list_defn;

(*val natural_to_le_byte_list_padded_to : natural -> natural -> list byte*)
 val _ = Define `
 (natural_to_le_byte_list_padded_to width n=    
  (let bytes = (natural_to_le_byte_list n)
    in 
    bytes ++ (replicate (width - length bytes) ((n2w : num -> 8 word(( 0:num)))))))`;


(*val n2i : natural -> integer*)
val _ = Define `
 (n2i=  int_of_num)`;


(*val i2n: integer -> natural*)
val _ = Define `
 (i2n=  (\ i. Num (ABS i)))`;


(*val i2n_signed : nat -> integer -> natural*)
val _ = Define `
 (i2n_signed width i=    
  (if i >=( 0 : int) then 
        if i >=(( 2 : int) ** (width -( 1 : num))) then failwith "overflow"
        else Num (ABS i)
    else 
        (* We manually encode the 2's complement of the negated value *)
        let negated = (Num (ABS (( 0 : int) - i))) in 
        let (xormask : num) = ((( 2:num) ** width) -( 1:num)) in
        let compl =(( 1:num) + natural_lxor negated xormask)
        in
        (*let _ = errln ("Signed value " ^ (show i) ^ " is 2's-compl'd to 0x" ^ (hex_string_of_natural compl))
        in*) compl))`;


(*val to_le_signed_bytes : natural -> integer -> list byte*)
val _ = Define `
 (to_le_signed_bytes bytewidth i=    
  (natural_to_le_byte_list_padded_to bytewidth (i2n_signed (((( 8:num)*bytewidth):num)) i)))`;


(*val to_le_unsigned_bytes : natural -> integer -> list byte*)
val _ = Define `
 (to_le_unsigned_bytes bytewidth i=    
  (natural_to_le_byte_list_padded_to bytewidth (Num (ABS i))))`;


(*val write_natural_field : natural -> natural -> element -> natural -> element*)
val _ = Define `
 (write_natural_field new_field_value width element1 offset=    
  (let pre_bytes = (take offset element1.contents)
    in
    let post_bytes = (drop (offset + width) element1.contents)
    in
    (* FIXME: avoid hard-coding little-endian *)
    let field_bytes = (natural_to_le_byte_list new_field_value)
    in
    if length field_bytes > width then failwith "internal error: relocation output unrepresentable"
    else
    <|
        contents := (((pre_bytes ++ (let x2 = 
  ([]) in  FOLDR (\b x2 .  if T then SOME b :: x2 else x2) x2 field_bytes))
            ++ (replicate (width - (length field_bytes)) (SOME ((n2w : num -> 8 word(( 0:num))))))) ++ post_bytes)
        ; startpos := (element1.startpos)
        ; length1 := (element1.length1)
     |>))`;

val _ = export_theory()

