Using built-in specs.
COLLECT_GCC=/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/x86_64-buildroot-linux-uclibc-gcc
COLLECT_LTO_WRAPPER=/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../libexec/gcc/x86_64-buildroot-linux-uclibc/4.9.3/lto-wrapper
Target: x86_64-buildroot-linux-uclibc
Configured with: ./configure --prefix=/home/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr --sysconfdir=/home/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/etc --localstatedir=/home/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/var --enable-shared --disable-static --disable-gtk-doc --disable-gtk-doc-html --disable-doc --disable-docs --disable-documentation --disable-debug --with-xmlto=no --with-fop=no --disable-dependency-tracking --target=x86_64-buildroot-linux-uclibc --with-sysroot=/home/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/x86_64-buildroot-linux-uclibc/sysroot --disable-__cxa_atexit --with-gnu-ld --disable-libssp --disable-multilib --with-gmp=/home/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr --with-mpfr=/home/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr --with-pkgversion='Buildroot 2015.08.1-hgdc22d1780053-dirty' --with-bugurl=http://bugs.buildroot.net/ --disable-libquadmath --disable-libsanitizer --enable-tls --disable-libmudflap --enable-threads --with-mpc=/home/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr --without-isl --without-cloog --disable-decimal-float --with-arch=nocona --enable-languages=c --disable-shared --without-headers --disable-threads --with-newlib --disable-largefile --disable-nls
Thread model: single
gcc version 4.9.3 (Buildroot 2015.08.1-hgdc22d1780053-dirty) 
COMPILER_PATH=/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../libexec/gcc/x86_64-buildroot-linux-uclibc/4.9.3/:/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../libexec/gcc/:/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../lib/gcc/x86_64-buildroot-linux-uclibc/4.9.3/../../../../x86_64-buildroot-linux-uclibc/bin/
LIBRARY_PATH=/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../lib/gcc/x86_64-buildroot-linux-uclibc/4.9.3/:/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../lib/gcc/:/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/lib/../lib64/:/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/usr/lib/../lib64/:/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/lib/:/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/usr/lib/
COLLECT_GCC_OPTIONS='-save-temps' '-o' 'true' '-static' '-fno-lto' '-mtune=generic' '-march=nocona'
 /var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../libexec/gcc/x86_64-buildroot-linux-uclibc/4.9.3/collect2 -fno-lto "--sysroot=/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot" -m elf_x86_64 -static -o true /var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/usr/lib/../lib64/crt1.o /var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/usr/lib/../lib64/crti.o /var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../lib/gcc/x86_64-buildroot-linux-uclibc/4.9.3/crtbeginT.o -L/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../lib/gcc/x86_64-buildroot-linux-uclibc/4.9.3 -L/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../lib/gcc -L/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/lib/../lib64 -L/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/usr/lib/../lib64 -L/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/lib -L/var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/usr/lib true.o "-Map=true.map" --no-relax --start-group -lgcc -lc --end-group /var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../lib/gcc/x86_64-buildroot-linux-uclibc/4.9.3/crtend.o /var/local/stephen/work/devel/rsem/system-v-abi/contrib/buildroot-2015.08.1/output/host/usr/bin/../x86_64-buildroot-linux-uclibc/sysroot/usr/lib/../lib64/crtn.o
