chapter {* Generated by Lem from elf_section_header_table.lem. *}

theory "Elf_section_header_tableAuxiliary" 

imports 
 	 Main "~~/src/HOL/Library/Code_Target_Numeral"
	 (* IMPORTS MASKED FOR ANONYMOUS REVIEW *)

begin 


(****************************************************)
(*                                                  *)
(* Termination Proofs                               *)
(*                                                  *)
(****************************************************)

termination read_elf32_section_header_table' by lexicographic_order

termination read_elf64_section_header_table' by lexicographic_order

termination get_elf32_section_to_segment_mapping by lexicographic_order

termination get_elf64_section_to_segment_mapping by lexicographic_order



end
