dummy:
	ocamlfind ocamlc -package bitstring.syntax -syntax camlp4o -I ../../lem/ocaml-lib/_build/ unix.cma bitstring.cma nums.cma nat_num.cmo lem.cmo lem_list.cmo error.ml utility.ml ml_bindings.ml elf_types.ml elf_header.ml main.ml
